image: Visual Studio 2017

max_jobs: 2

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      INSTALLER_ARCH: "amd64"
      RUST_HOST: x86_64-pc-windows-msvc
    - PYTHON: "C:\\Python36"
      INSTALLER_ARCH: "win32"
      RUST_HOST: i686-pc-windows-msvc

platform:
  - x86
  - x64

matrix:
  exclude:
    - platform: x86
      INSTALLER_ARCH: "amd64"
    - platform: x64
      INSTALLER_ARCH: "win32"

install:
  - SET PATH=%PATH%;C:\Program Files (x86)\NSIS\Bin

  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - .\rustup-init.exe --default-host %RUST_HOST% --default-toolchain stable -y
  - SET PATH=%PATH%;C:\Users\appveyor\.cargo\bin

  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install --upgrade pipenv
  - pipenv sync --system --dev

  - SET PATH

build_script:
  - for /f %%i in ('git describe') do @set REPO_GIT_VERSION=%%i
  - invoke installers.build --version=%REPO_GIT_VERSION% --no-clean
  - SET SETUP_EXE=pythonup-setup-%INSTALLER_ARCH%-%REPO_GIT_VERSION%.exe

after_build:
  - appveyor PushArtifact .\installers\%SETUP_EXE%

test_script:
  - flake8 .
  - pytest tests
  - invoke shims.test

  - docker build --build-arg SETUP_EXE=%SETUP_EXE% .\installers
